apiVersion: v1
kind: Service
metadata:
  name: {{ include "sekha.fullname" . }}-core
  labels:
    {{- include "sekha.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  type: {{ .Values.controller.service.type }}
  ports:
    - port: {{ .Values.controller.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sekha.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
